### PR TITLE
Fixes issue 1969: STs that are attached to a TGT are not counted in t…

### LINKED ISSUE #1969: STs that are attached to a TGT are not counted in total ticket cleanup
...while using the default ticket registry. This results in inconsistent ticket count reporting while cleaning.
Cleanup for 5 separate logins (5 TGTs + 5 STs), cleaner reports ~7-9 tickets cleaned.

Re-attaching the log file for reference.
[cas.zip](https://github.com/apereo/cas/files/437531/cas.zip)

CAS 4.2.5-SNAPSHOT
Tomcat 7, Java 8.
https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/ZMerMRq_EWg

### PR DESCRIPTION
**Pull request by wcrowell**
Closes #1969 

- Changed org.jasig.cas.ticket.registry.TicketRegistry's deleteTicket method to return the total count of tickets deleted which includes any child tickets.
- Unit tests have been updated to account for this change.

### CODE REVIEW

File: cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/TicketRegistryCleaner.java [hunk 1]
```diff
@@ -112,26 +114,33 @@ public void execute(final JobExecutionContext jobExecutionContext) throws JobExe
...
-                        return true;
                     }
-                    return false;
+                    return count;
                 }
             });
-            logger.info("{} expired tickets found and removed.", ticketsToRemove.size());
+            
+            int cumulativeCount = 0;
+            for (final int count : deletedTicketCounts) {
```
Comment (mmoayyed) [inline cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/TicketRegistryCleaner.java]: Why this and not `deletedTicketCounts.size()` ?

Comment (mmoayyed) [inline cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/TicketRegistryCleaner.java]: Ah never mind. I see it.

**Comment by mmoayyed** [comment]
Looks good to me. Thank you. Would you want to apply the same tactic to the master branch as well with a PR?

**Comment by wcrowell** [comment]
Yes, I can do that.  One thing I noticed in the unit tests is that when you create a TGT and then an ST off it and then a PGT, the call to deleteTicket is 2.  I started debugging through it last night and saw the same thing.  The PGT ends up being deleted already from the cache.  I noticed this with the EHCache ticket registry tests.  Just odd.

**Comment by wcrowell** [comment]
There is still something that does not look right here.  I am continuing to look at this.  

In this test I ran there should be 4 deleted tickets but the log shows 3.  The 4 tickets are:

PT-2-dXQFicsSO9Q1se4eQcRV-cas01.example.org
PGT-**********************************************2BYKAaXTBc-cas01.example.org
TGT-**********************************************uHyxQxEgK2-cas01.example.org
ST-1-KJD6gJAwUokZriRtsFJP-cas01.example.org

Log:


```
2016-08-29 09:19:24,294 DEBUG [org.jasig.cas.ticket.registry.TicketRegistryCleaner] - <Cleaning up expired service ticket [PT-2-dXQFicsSO9Q1se4eQcRV-cas01.example.org]>
2016-08-29 09:19:24,294 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Attempting to retrieve ticket [PT-2-dXQFicsSO9Q1se4eQcRV-cas01.example.org]>
2016-08-29 09:19:24,294 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Ticket [PT-2-dXQFicsSO9Q1se4eQcRV-cas01.example.org] found in registry.>
2016-08-29 09:19:24,294 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Removing ticket [PT-2-dXQFicsSO9Q1se4eQcRV-cas01.example.org] from the registry.>
2016-08-29 09:19:24,294 DEBUG [org.jasig.cas.ticket.registry.TicketRegistryCleaner] - <Cleaning up expired ticket-granting ticket [PGT-**********************************************2BYKAaXTBc-cas01.example.org]>
2016-08-29 09:19:24,307 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Attempting to retrieve ticket [PGT-**********************************************2BYKAaXTBc-cas01.example.org]>
2016-08-29 09:19:24,307 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Ticket [PGT-**********************************************2BYKAaXTBc-cas01.example.org] found in registry.>
2016-08-29 09:19:24,307 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Removing proxy-granting ticket [PGT-**********************************************2BYKAaXTBc-cas01.example.org]>
2016-08-29 09:19:24,307 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Removing children of ticket [PGT-**********************************************2BYKAaXTBc-cas01.example.org] from the registry.>
2016-08-29 09:19:24,307 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Unable to remove ticket [PT-2-dXQFicsSO9Q1se4eQcRV-cas01.example.org]>
2016-08-29 09:19:24,307 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Removing ticket [PGT-**********************************************2BYKAaXTBc-cas01.example.org] from the registry.>
2016-08-29 09:19:24,308 DEBUG [org.jasig.cas.ticket.registry.TicketRegistryCleaner] - <Cleaning up expired ticket-granting ticket [TGT-**********************************************uHyxQxEgK2-cas01.example.org]>
2016-08-29 09:19:24,309 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Attempting to retrieve ticket [TGT-**********************************************uHyxQxEgK2-cas01.example.org]>
2016-08-29 09:19:24,309 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Ticket [TGT-**********************************************uHyxQxEgK2-cas01.example.org] found in registry.>
2016-08-29 09:19:24,309 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Removing children of ticket [TGT-**********************************************uHyxQxEgK2-cas01.example.org] from the registry.>
2016-08-29 09:19:24,309 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Unable to remove ticket [ST-1-KJD6gJAwUokZriRtsFJP-cas01.example.org]>
2016-08-29 09:19:24,309 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Attempting to retrieve ticket [PGT-**********************************************2BYKAaXTBc-cas01.example.org]>
2016-08-29 09:19:24,309 DEBUG [org.jasig.cas.ticket.registry.DefaultTicketRegistry] - <Removing ticket [TGT-**********************************************uHyxQxEgK2-cas01.example.org] from the registry.>
2016-08-29 09:19:24,309 INFO [org.jasig.cas.ticket.registry.TicketRegistryCleaner] - <3 expired tickets found and removed.>
```

**Comment by wcrowell** [comment]
Ok, I think I see what is happening.  The Proxy Granting Tickets are not included in the final total because they are not separate entries in the cache implementation.  They are part of the Service Ticket.  Service Tickets and TGTs are separate entries.  I can increment the deleted ticket count when I encounter a Proxy Granting Ticket if you want.  Let me know.

**Comment by mmoayyed** [comment]
>I can increment the deleted ticket count when I encounter a Proxy Granting Ticket if you want.

Yes, please do. The count should reflect everything that is actually deleted.

**Comment by wcrowell** [comment]
Will do.
