### PR TITLE
Use @Transactional when handling JPA ticket/service ops

### LINKED ISSUE #1817: No EntityManager exception with JpaTicketRegistry, CAS 4.2.2
1 CAS server version: **4.2.2**
2 Container/environment type/version: **Tomcat 8.0.35, Windows, Java 8**
3 Steps to duplicate the problem

- Deploy cas.war

- Log in with default user casTest::Mellon

- Wait forJPA Ticket Registry cleaning

4 Overlay: https://github.com/cas-projects/cas-issues/tree/master/cas-issue-1817
5 Stacktraces and CAS logs
```
2016-06-03 12:32:38,861 ERROR [org.jasig.cas.ticket.registry.JpaTicketRegistry] - <no transaction is in progress
javax.persistence.TransactionRequiredException: no transaction is in progress
        at org.hibernate.jpa.spi.AbstractQueryImpl.checkTransaction(AbstractQueryImpl.java:205)
        at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:433)
        at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:364)
        at com.sun.proxy.$Proxy88.getResultList(Unknown Source)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicketAndChildren(JpaTicketRegistry.java:120)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicket_aroundBody4(JpaTicketRegistry.java:104)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$AjcClosure5.run(JpaTicketRegistry.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicket(JpaTicketRegistry.java:91)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply_aroundBody0(JpaTicketRegistry.java:287)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$1$AjcClosure1.run(JpaTicketRegistry.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply(JpaTicketRegistry.java:282)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply(JpaTicketRegistry.java:1)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.Iterators.size(Iterators.java:191)
        at com.google.common.collect.Collections2$FilteredCollection.size(Collections2.java:211)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.execute_aroundBody16(JpaTicketRegistry.java:299)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$AjcClosure17.run(JpaTicketRegistry.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44)
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.execute(JpaTicketRegistry.java:266)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
>
```

Also in one deployment I got this error
```
2016-05-30 19:40:21,108 ERROR [org.jasig.cas.ticket.registry.JpaTicketRegistry] - Error removing ST-5-7RnrfSjskMvCiYgc7E9d-example.org from registry.
javax.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread - cannot reliably process 'remove' call
 at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:277) ~[spring-orm-4.2.3.RELEASE.jar:4.2.3.RELEASE]
 at com.sun.proxy.$Proxy69.remove(Unknown Source) ~[?:?]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry.removeTicket(JpaTicketRegistry.java:149) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicket_aroundBody4(JpaTicketRegistry.java:99) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$AjcClosure5.run(JpaTicketRegistry.java:1) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjweaver-1.8.6.jar:1.8.6]
 at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44) ~[inspektr-aspects-1.3.GA.jar:1.3.GA]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicket(JpaTicketRegistry.java:91) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply_aroundBody0(JpaTicketRegistry.java:290) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$1$AjcClosure1.run(JpaTicketRegistry.java:1) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjweaver-1.8.6.jar:1.8.6]
 at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44) ~[inspektr-aspects-1.3.GA.jar:1.3.GA]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply(JpaTicketRegistry.java:282) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$1.apply(JpaTicketRegistry.java:1) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652) ~[guava-18.0.jar:?]
 at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[guava-18.0.jar:?]
 at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[guava-18.0.jar:?]
 at com.google.common.collect.Iterators.size(Iterators.java:191) ~[guava-18.0.jar:?]
 at com.google.common.collect.Collections2$FilteredCollection.size(Collections2.java:211) ~[guava-18.0.jar:?]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry.execute_aroundBody16(JpaTicketRegistry.java:299) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry$AjcClosure17.run(JpaTicketRegistry.java:1) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjweaver-1.8.6.jar:1.8.6]
 at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44) ~[inspektr-aspects-1.3.GA.jar:1.3.GA]
 at org.jasig.cas.ticket.registry.JpaTicketRegistry.execute(JpaTicketRegistry.java:266) ~[cas-server-support-jpa-ticket-registry-4.2.2.jar:4.2.2]
 at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.1.jar:?]
 at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.2.1.jar:?]
```

https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/-G08-1LDiBk

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes #1817 

Backported the service registry initialization feature from master as well. Tested with both Service and Ticket JPA registries and HSQLDB 2.3.4.

### CODE REVIEW

**Comment by mmoayyed** [comment]
This is also relevant for #1772

File: cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/DefaultAuthenticationTransactionManager.java [hunk 1]
```diff
@@ -15,13 +13,11 @@
...
 @Component("defaultAuthenticationTransactionManager")
-public final class DefaultAuthenticationTransactionManager implements AuthenticationTransactionManager {
+public class DefaultAuthenticationTransactionManager implements AuthenticationTransactionManager {
 
     private static final Logger LOGGER = LoggerFactory.getLogger(DefaultAuthenticationTransactionManager.class);
 
-    @NotNull
-    @Autowired
-    @Qualifier("authenticationManager")
+    @Resource(name="authenticationManager")
```
Comment (dima767) [inline cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/DefaultAuthenticationTransactionManager.java]: Just a note on the unrelated work I'm doing on another - I do the opposite i.e. replacing the use of `@Resource` with `@Autowired @Qualifier` combination to be consistent throughout our config infrastructure

Comment (dima767) [inline cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/DefaultAuthenticationTransactionManager.java]: For consistency and also `@Resource` did not work for me in one scenarios (don't remember which. Could be constructor injection, etc.). In general `@Autowired` is more powerful and leverages the full power of Spring, etc. Let's pick a autowiring injection style and stick to it.

Comment (mmoayyed) [inline cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/DefaultAuthenticationTransactionManager.java]: Sounds good. I'll swich over.

Comment (dima767) [inline cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/DefaultAuthenticationTransactionManager.java]: Thank you!

Comment (dima767) [inline cas-server-core-authentication/src/main/java/org/jasig/cas/authentication/DefaultAuthenticationTransactionManager.java]: Otherwise, +1 on the change from me.
