### PR TITLE
SAML authentication delegation is broken

### LINKED ISSUE #2020: SAML authentication delegation is broken
The `resource:` or `classpath:` prefix cannot be used and I've updated the warning about it: https://github.com/apereo/cas/commit/1a77b24956dd3a07736361e689f3ca863f8cde20#diff-6fb367a9c97b816b0c1991fcbde08088

I have made various fixes on pac4j v1.9.3 to make it work: https://github.com/pac4j/pac4j/pull/691

Though, the SAML support cannot still work because of the fact we use the redirection URL (https://github.com/apereo/cas/blob/master/support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/web/flow/ClientAction.java#L161) while by default, it's a form POST. And there is no property to change that.

Using an intermediate controller or switch to HTTP REDIRECT binding would be a solution.

### PR DESCRIPTION
**Pull request by leleuj**
Closes #2020

### CODE REVIEW

File: support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/web/flow/ClientAction.java [hunk 1]
```diff
@@ -110,7 +110,7 @@ protected Event doExecute(final RequestContext context) throws Exception {
                 response.flushBuffer();
                 final ExternalContext externalContext = ExternalContextHolder.getExternalContext();
                 externalContext.recordResponseComplete();
-                return new Event(this, STOP_WEBFLOW);
+                return new Event(this, STOP);
```
Comment (mmoayyed) [inline support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/web/flow/ClientAction.java]: Do we have an event definition called "stop" ?

Comment (mmoayyed) [inline support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/web/flow/ClientAction.java]: Ah never mind. I see `actionState.getTransitionSet().add(createTransition(ClientAction.STOP, ClientAction.STOP_WEBFLOW));`

File: support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/Pac4jConfiguration.java [hunk 2]
```diff
@@ -170,7 +170,8 @@ private void configureSamlClient(final Map<String, String> properties) {
         properties.put(PropertiesConfigFactory.SAML_SERVICE_PROVIDER_ENTITY_ID,
                 casProperties.getAuthn().getPac4j().getSaml().getServiceProviderEntityId());
         properties.put(PropertiesConfigFactory.SAML_SERVICE_PROVIDER_METADATA_PATH,
-                casProperties.getAuthn().getPac4j().getSaml().getServiceProviderEntityId());
+                casProperties.getAuthn().getPac4j().getSaml().getServiceProviderMetadataPath());
+        properties.put(PropertiesConfigFactory.SAML_DESTINATION_BINDING_TYPE, "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect");
```
Comment (leleuj) [inline support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/Pac4jConfiguration.java]: Yes, I hesitated on this. But the `opensaml` dependency is not pulled, and I thought maybe it was not necessary since we may only use Facebook for example.

Comment (mmoayyed) [inline support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/Pac4jConfiguration.java]: In any case, no big deal.

**Comment by mmoayyed** [comment]
Final thoughts; we good here, or is there still work being done on the error handling and SWF?

File: support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/Pac4jConfiguration.java (hunk 2 above)
Comment (leleuj) [inline support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/Pac4jConfiguration.java]: Totally right. My IDE didn't want to import the SAMLConstants.

**Comment by leleuj** [comment]
Everything is ok, except the error handling with SWF.

**Comment by mmoayyed** [comment]
I can definitely take a look. How would I reproduce this? use Facebook as a provider and force a bad scope?

File: support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/Pac4jConfiguration.java (hunk 2 above)
Comment (leleuj) [inline support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/config/Pac4jConfiguration.java]: And it does not compile. I will move the `libraries.opensaml` from `runtime` to `compile` scope if you don't have any concern with that.

**Comment by leleuj** [comment]
You need this PR and the demo: https://github.com/leleuj/cas-pac4j-oauth-demo which is already configured to fail for Facebook ;-)

**Comment by mmoayyed** [comment]
Cool. Lets merge then, and diagnose further.

**Comment by leleuj** [comment]
You merged before I pushed the change with the SAMLConstant, but anyway, this is a detail.

**Comment by mmoayyed** [comment]
Yup. That could be a quick fix; I am slightly more worried about the error handling portion. Let me take a quick peek and I'll post back with your demo's results.

**Comment by mmoayyed** [comment]
In `ClientAction`, remove the following from the catch block:

```
response.flushBuffer();
final ExternalContext externalContext = ExternalContextHolder.getExternalContext();
externalContext.recordResponseComplete();
```

**Comment by mmoayyed** [comment]
Also, we should do a little bit of refactoring:

1. Examine the http request in client action and if the request has error codes, etc, immediately route the flow to the STOP flow id, and pass along model variables to note details on the page.
2. Clean up the pac4j resolver a bit to share logic, since it does mostly the same stuff.

**Comment by mmoayyed** [comment]
@leleuj did you want me to continue with a PR, or would you rather handle the above ?

**Comment by mmoayyed** [comment]
I made a few tweaks to better handle error handling. Going to push shortly.

**Comment by leleuj** [comment]
I'll let you handle the adjustments then.

About point 1., handling error codes is the responsibility of the client so I don't think you should refactor things here.
