### PR TITLE
Fix JPA Service Registry: Public Key Location cast to Blob

### LINKED ISSUE #1842: JPA Service Registry: Public Key Location causes a "Can not cast to java.sql.Blob" error.
### **Issue**
Server : Tomcat 7
CAS Mgmt version : 4.2.2

Set Public Key Location in managment webapp (classpath:services/cert.der or /opt/cert.der) cause a cannot be cast to java.sql.Blob.

[sqlblob-issues.txt](https://github.com/apereo/cas/files/323178/sqlblob-issues.txt)

### PR DESCRIPTION
**Pull request by mmoayyed**
Closes #1842

### CODE REVIEW

File: cas-server-core-services/src/main/java/org/jasig/cas/services/RegisteredServicePublicKeyImpl.java [hunk 1]
```diff
@@ -10,15 +10,14 @@
...
 /**
  * Represents a public key for a CAS registered service.
  * @author Misagh Moayyed
  * @since 4.1
  */
-public final class RegisteredServicePublicKeyImpl implements Serializable, RegisteredServicePublicKey {
+public class RegisteredServicePublicKeyImpl implements RegisteredServicePublicKey {
     private static final long serialVersionUID = -8497658523695695863L;
 
     private final transient Logger logger = LoggerFactory.getLogger(this.getClass());
```
Comment (dima767) [inline cas-server-core-services/src/main/java/org/jasig/cas/services/RegisteredServicePublicKeyImpl.java]: Should this instance be made static instead for the JPA blob deserialization ?

Comment (mmoayyed) [inline cas-server-core-services/src/main/java/org/jasig/cas/services/RegisteredServicePublicKeyImpl.java]: Good point. sure.
